abbr -a -- gs 'git status'
abbr -a -- lsl 'ls -lh'
abbr -a -- abbra 'abbr -a'
abbr -a -- gcl 'git clone'
abbr -a -- gaa 'git add --all'
abbr -a -- ga 'git add'
abbr -a -- gst 'git stash'
abbr -a -- gco 'git checkout'
abbr -a -- gb 'git branch'
abbr -a -- brup 'brew update'
abbr -a -- prupg 'brew upgrade'
abbr -a -- brs 'brew search'
abbr -a -- bri 'brew info'
abbr -a -- lsla 'ls -alh'
abbr -a -- lsal 'ls -alh'
abbr -a -- gc 'git commit'
abbr -a -- gcm 'git commit -m'
abbr -a -- gl 'git log'
abbr -a -- brin 'brew install'
abbr -a -- brun 'brew uninstall'
abbr -a -- brh 'brew home'
abbr -a --set-cursor='%' -- abbras 'abbr -a %; abbr > ~/.dotfiles/user/.config/fish/conf.d/myabbrs.fish'
abbr -a -- trans transmission-remote
abbr -a -- transd transmission-daemon
abbr -a -- abbrs 'abbr > ~/.dotfiles/user/.config/fish/conf.d/myabbrs.fish'
abbr -a -- suspend 'sudo shutdown -s now'
abbr -a -- reboot 'sudo shutdown -r now'
abbr -a -- halt 'sudo shutdown -h now'
abbr -a --set-cursor='%' -- gcam 'git commit --all -m %'
abbr -a -- ts tailscale
abbr -a -- k kubectl
abbr -a -- kgp 'kubectl get pods'
