abbr -a -- gs 'git status'
abbr -a -- lsl 'ls -lh'
abbr -a -- abbra 'abbr -a'
abbr -a -- gcl 'git clone'
abbr -a -- gaa 'git add --all'
abbr -a -- ga 'git add'
abbr -a -- gst 'git stash'
abbr -a -- gco 'git checkout'
abbr -a -- gb 'git branch'
abbr -a -- brup 'brew update'
abbr -a -- prupg 'brew upgrade'
abbr -a -- brs 'brew search'
abbr -a -- bri 'brew info'
abbr -a -- bl 'brew list'
abbr -a -- bup 'brew update'
abbr -a -- bupg 'brew upgrade'
abbr -a -- bs 'brew search'
abbr -a -- bi 'brew info'
abbr -a -- bin 'brew install'
abbr -a -- bun 'brew uninstall'
abbr -a -- blg 'brew list | grep'
abbr -a -- lsla 'ls -alh'
abbr -a -- lsal 'ls -alh'
